# Generated by Django 4.2.2 on 2023-06-20 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0002_cliente_factura_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, null=True)),
                ('cantidad', models.IntegerField(null=True)),
                ('precio', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factura.producto'),
        ),
    ]
