# Generated by Django 4.2.2 on 2023-06-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0003_producto_factura_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
