# Generated by Django 4.2.2 on 2023-07-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0005_rename_codigo_factura_factura_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.IntegerField(null=True)),
                ('nombre', models.CharField(max_length=50, null=True)),
                ('direccion', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
