# Generated by Django 4.2.2 on 2023-07-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factura', '0006_proveedor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='Proveedores',
        ),
        migrations.AddField(
            model_name='factura',
            name='proveedores',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='factura.proveedores'),
        ),
    ]
